name: unity-webgl-upload-action
description: Test target deployment for unity webgl upload action
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
